# Cartera de Inversiones - Add-on para Home Assistant (VERSIÓN FINAL)
# https://developers.home-assistant.io/docs/add-ons/configuration

name: Cartera FINAL
description: Cartera de inversiones (acciones, ETFs, fondos, criptos) con Streamlit. Datos en share/cartera_final (Samba). Puerto 8503.
version: "1.0.5"
slug: cartera_final
url: "https://github.com/aupacheca/cartera_final"
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
  - i386
init: false
map:
  - addon_config:rw
  - share:rw
ports:
  "8503/tcp": 8503
ports_description:
  "8503": "Interfaz web Streamlit"
options:
  data_path: "/share/cartera_final"
schema:
  data_path: str
